#pragma once
#include <esf/geometry/algorithm/area.hpp>
#include <esf/geometry/algorithm/bounding_rect.hpp>
#include <esf/geometry/algorithm/center.hpp>
#include <esf/geometry/algorithm/circumcentre.hpp>
#include <esf/geometry/algorithm/contains.hpp>
#include <esf/geometry/algorithm/distance.hpp>
#include <esf/geometry/algorithm/equals.hpp>
#include <esf/geometry/algorithm/length.hpp>
