#pragma once
#include <esf/geometry/algorithm.hpp>
#include <esf/geometry/compare.hpp>
#include <esf/geometry/geometry.hpp>
#include <esf/geometry/linear_grid.hpp>
#include <esf/geometry/linestring.hpp>
#include <esf/geometry/point1.hpp>
#include <esf/geometry/point2.hpp>
#include <esf/geometry/points2.hpp>
#include <esf/geometry/polygon.hpp>
#include <esf/geometry/rect.hpp>
//#include <esf/geometry/segment.hpp>
