#pragma once
#include <esf/boundary_cond.hpp>
#include <esf/element.hpp>
#include <esf/function.hpp>
#include <esf/io.hpp>
#include <esf/matrix_based/seq_cell_assembler.hpp>
#include <esf/matrix_based/solver.hpp>
#include <esf/mesh/mesh1.hpp>
#include <esf/mesh/mesh2.hpp>
#include <esf/system.hpp>
#include <esf/var.hpp>
